package musicPlayer.ui;

public enum UIView {
    MAIN_MENU,
    PLAYLIST_LIST_VIEW,
    PLAYLIST_MENU,
    SELECTING_A_PLAYLIST,
    SELECTING_A_SONG_TO_PLAY,
    PLAYING_SELECTED_SONG,
    SHOWING_ALL_SONGS_ON_PLAYLIST
}
